
INSERT INTO events (title, category, priority, user_id, start_date, end_date)
VALUES
    ('Coffee with Friend', 'SOCIALISATION', true, 1, NOW(), NOW() + INTERVAL '2 hours'),
    ('Running', 'SPORTS', true, 2, NOW() + INTERVAL '1 day', NOW() + INTERVAL '1 day' + INTERVAL '1 hour'),
    ('Concert', 'SOCIALISATION', true, 3, NOW() + INTERVAL '2 days', NOW() + INTERVAL '2 days' + INTERVAL '3 hours'),
    ('Cooking the Dinner', 'CHORES', true, 4, NOW() + INTERVAL '3 days', NOW() + INTERVAL '3 days' + INTERVAL '2 hours'),
    ('Gym Workout', 'SPORTS', true, 5, NOW() + INTERVAL '4 days', NOW() + INTERVAL '4 days' + INTERVAL '1.5 hours'),
    ('Reading', 'RELAXATION', true, 6, NOW() + INTERVAL '5 days', NOW() + INTERVAL '5 days' + INTERVAL '2 hours'),
    ('Work Meeting', 'WORK', true, 7, NOW() + INTERVAL '6 days', NOW() + INTERVAL '6 days' + INTERVAL '1.5 hours'),
    ('Yoga', 'HEALTH', true, 8, NOW() + INTERVAL '7 days', NOW() + INTERVAL '7 days' + INTERVAL '1.5 hours'),
    ('Movie Night', 'RELAXATION', true, 9, NOW() + INTERVAL '8 days', NOW() + INTERVAL '8 days' + INTERVAL '3 hours'),
    ('Shopping', 'CHORES', true, 10, NOW() + INTERVAL '9 days', NOW() + INTERVAL '9 days' + INTERVAL '2 hours'),
    ('Lunch with Family', 'SOCIALISATION', true, 11, NOW() + INTERVAL '10 days', NOW() + INTERVAL '10 days' + INTERVAL '1.5 hours'),
    ('Hiking', 'SPORTS', true, 12, NOW() + INTERVAL '11 days', NOW() + INTERVAL '11 days' + INTERVAL '2 hours'),
    ('Art Exhibition', 'SOCIALISATION', true, 13, NOW() + INTERVAL '12 days', NOW() + INTERVAL '12 days' + INTERVAL '3 hours'),
    ('Baking Cookies', 'CHORES', true, 14, NOW() + INTERVAL '13 days', NOW() + INTERVAL '13 days' + INTERVAL '2.5 hours'),
    ('Swimming', 'SPORTS', true, 15, NOW() + INTERVAL '14 days', NOW() + INTERVAL '14 days' + INTERVAL '1.5 hours'),
    ('Meditation', 'RELAXATION', true, 16, NOW() + INTERVAL '15 days', NOW() + INTERVAL '15 days' + INTERVAL '1 hour'),
    ('Team Workshop', 'WORK', true, 17, NOW() + INTERVAL '16 days', NOW() + INTERVAL '16 days' + INTERVAL '2 hours'),
    ('Cycling', 'SPORTS', true, 18, NOW() + INTERVAL '17 days', NOW() + INTERVAL '17 days' + INTERVAL '1.5 hours'),
    ('Game Night', 'RELAXATION', true, 19, NOW() + INTERVAL '18 days', NOW() + INTERVAL '18 days' + INTERVAL '3 hours'),
    ('Home Cleaning', 'CHORES', true, 20, NOW() + INTERVAL '19 days', NOW() + INTERVAL '19 days' + INTERVAL '2 hours'),
    ('Dinner Party', 'SOCIALISATION', true, 21, NOW() + INTERVAL '20 days', NOW() + INTERVAL '20 days' + INTERVAL '3 hours'),
    ('Morning Jog', 'SPORTS', true, 22, NOW() + INTERVAL '21 days', NOW() + INTERVAL '21 days' + INTERVAL '1 hour'),
    ('Music Festival', 'SOCIALISATION', true, 23, NOW() + INTERVAL '22 days', NOW() + INTERVAL '22 days' + INTERVAL '5 hours'),
    ('Grilling BBQ', 'CHORES', true, 24, NOW() + INTERVAL '23 days', NOW() + INTERVAL '23 days' + INTERVAL '2.5 hours'),
    ('Yoga Retreat', 'HEALTH', true, 25, NOW() + INTERVAL '24 days', NOW() + INTERVAL '24 days' + INTERVAL '6 hours'),
    ('Gardening', 'CHORES', true, 26, NOW() + INTERVAL '25 days', NOW() + INTERVAL '25 days' + INTERVAL '2 hours'),
    ('Team Building Event', 'WORK', true, 27, NOW() + INTERVAL '26 days', NOW() + INTERVAL '26 days' + INTERVAL '4 hours'),
    ('Rock Climbing', 'SPORTS', true, 28, NOW() + INTERVAL '27 days', NOW() + INTERVAL '27 days' + INTERVAL '2.5 hours'),
    ('Reading Club', 'SOCIALISATION', true, 29, NOW() + INTERVAL '28 days', NOW() + INTERVAL '28 days' + INTERVAL '1.5 hours'),
    ('Home Renovation', 'CHORES', true, 30, NOW() + INTERVAL '29 days', NOW() + INTERVAL '29 days' + INTERVAL '8 hours'),
    ('Tech Meetup', 'WORK', true, 31, NOW() + INTERVAL '30 days', NOW() + INTERVAL '30 days' + INTERVAL '3 hours'),
    ('Beach Volleyball', 'SPORTS', true, 32, NOW() + INTERVAL '31 days', NOW() + INTERVAL '31 days' + INTERVAL '2 hours'),
    ('Cooking Class', 'CHORES', true, 33, NOW() + INTERVAL '32 days', NOW() + INTERVAL '32 days' + INTERVAL '2.5 hours'),
    ('Networking Event', 'SOCIALISATION', true, 34, NOW() + INTERVAL '33 days', NOW() + INTERVAL '33 days' + INTERVAL '4 hours'),
    ('Painting Workshop', 'RELAXATION', true, 35, NOW() + INTERVAL '34 days', NOW() + INTERVAL '34 days' + INTERVAL '2 hours'),
    ('Volunteering', 'SOCIALISATION', true, 36, NOW() + INTERVAL '35 days', NOW() + INTERVAL '35 days' + INTERVAL '5 hours'),
    ('Business Trip', 'WORK', true, 37, NOW() + INTERVAL '36 days', NOW() + INTERVAL '36 days' + INTERVAL '8 hours'),
    ('Dance Class', 'SPORTS', true, 38, NOW() + INTERVAL '37 days', NOW() + INTERVAL '37 days' + INTERVAL '1.5 hours'),
    ('Stargazing', 'RELAXATION', true, 39, NOW() + INTERVAL '38 days', NOW() + INTERVAL '38 days' + INTERVAL '2 hours'),
    ('Home Office Day', 'WORK', true, 40, NOW() + INTERVAL '39 days', NOW() + INTERVAL '39 days' + INTERVAL '8 hours'),
    ('Family Picnic', 'SOCIALISATION', true, 41, NOW() + INTERVAL '40 days', NOW() + INTERVAL '40 days' + INTERVAL '4 hours'),
    ('Mountain Biking', 'SPORTS', true, 42, NOW() + INTERVAL '41 days', NOW() + INTERVAL '41 days' + INTERVAL '2.5 hours'),
    ('Book Club Meeting', 'SOCIALISATION', true, 43, NOW() + INTERVAL '42 days', NOW() + INTERVAL '42 days' + INTERVAL '1.5 hours'),
    ('DIY Home Project', 'CHORES', true, 44, NOW() + INTERVAL '43 days', NOW() + INTERVAL '43 days' + INTERVAL '5 hours'),
    ('Spa Day', 'RELAXATION', true, 45, NOW() + INTERVAL '44 days', NOW() + INTERVAL '44 days' + INTERVAL '6 hours'),
    ('Workout Class', 'SPORTS', true, 46, NOW() + INTERVAL '45 days', NOW() + INTERVAL '45 days' + INTERVAL '1.5 hours'),
    ('Podcast Recording', 'WORK', true, 47, NOW() + INTERVAL '46 days', NOW() + INTERVAL '46 days' + INTERVAL '2 hours'),
    ('Photography Expedition', 'RELAXATION', true, 48, NOW() + INTERVAL '47 days', NOW() + INTERVAL '47 days' + INTERVAL '4 hours'),
    ('Karaoke Night', 'SOCIALISATION', true, 49, NOW() + INTERVAL '48 days', NOW() + INTERVAL '48 days' + INTERVAL '3 hours'),
    ('Financial Planning', 'WORK', true, 50, NOW() + INTERVAL '49 days', NOW() + INTERVAL '49 days' + INTERVAL '2 hours');

UPDATE events
SET user_id = events.user_id + 50
WHERE user_id BETWEEN 1 AND 50;


INSERT INTO events (title, category, priority, user_id, start_date, end_date)
VALUES
    ('Coffee with Friend', 'SOCIALISATION', true, 1, NOW(), NOW() + INTERVAL '2 hours'),
    ('Running', 'SPORTS', true, 2, NOW() + INTERVAL '1 day', NOW() + INTERVAL '1 day' + INTERVAL '1 hour'),
    ('Concert', 'SOCIALISATION', true, 3, NOW() + INTERVAL '2 days', NOW() + INTERVAL '2 days' + INTERVAL '3 hours'),
    ('Cooking the Dinner', 'CHORES', true, 4, NOW() + INTERVAL '3 days', NOW() + INTERVAL '3 days' + INTERVAL '2 hours'),
    ('Gym Workout', 'SPORTS', true, 5, NOW() + INTERVAL '4 days', NOW() + INTERVAL '4 days' + INTERVAL '1.5 hours'),
    ('Reading', 'RELAXATION', true, 6, NOW() + INTERVAL '5 days', NOW() + INTERVAL '5 days' + INTERVAL '2 hours'),
    ('Work Meeting', 'WORK', true, 7, NOW() + INTERVAL '6 days', NOW() + INTERVAL '6 days' + INTERVAL '1.5 hours'),
    ('Yoga', 'HEALTH', true, 8, NOW() + INTERVAL '7 days', NOW() + INTERVAL '7 days' + INTERVAL '1.5 hours'),
    ('Movie Night', 'RELAXATION', true, 9, NOW() + INTERVAL '8 days', NOW() + INTERVAL '8 days' + INTERVAL '3 hours'),
    ('Shopping', 'CHORES', true, 10, NOW() + INTERVAL '9 days', NOW() + INTERVAL '9 days' + INTERVAL '2 hours'),
    ('Lunch with Family', 'SOCIALISATION', true, 11, NOW() + INTERVAL '10 days', NOW() + INTERVAL '10 days' + INTERVAL '1.5 hours'),
    ('Hiking', 'SPORTS', true, 12, NOW() + INTERVAL '11 days', NOW() + INTERVAL '11 days' + INTERVAL '2 hours'),
    ('Art Exhibition', 'SOCIALISATION', true, 13, NOW() + INTERVAL '12 days', NOW() + INTERVAL '12 days' + INTERVAL '3 hours'),
    ('Baking Cookies', 'CHORES', true, 14, NOW() + INTERVAL '13 days', NOW() + INTERVAL '13 days' + INTERVAL '2.5 hours'),
    ('Swimming', 'SPORTS', true, 15, NOW() + INTERVAL '14 days', NOW() + INTERVAL '14 days' + INTERVAL '1.5 hours'),
    ('Meditation', 'RELAXATION', true, 16, NOW() + INTERVAL '15 days', NOW() + INTERVAL '15 days' + INTERVAL '1 hour'),
    ('Team Workshop', 'WORK', true, 17, NOW() + INTERVAL '16 days', NOW() + INTERVAL '16 days' + INTERVAL '2 hours'),
    ('Cycling', 'SPORTS', true, 18, NOW() + INTERVAL '17 days', NOW() + INTERVAL '17 days' + INTERVAL '1.5 hours'),
    ('Game Night', 'RELAXATION', true, 19, NOW() + INTERVAL '18 days', NOW() + INTERVAL '18 days' + INTERVAL '3 hours'),
    ('Home Cleaning', 'CHORES', true, 20, NOW() + INTERVAL '19 days', NOW() + INTERVAL '19 days' + INTERVAL '2 hours'),
    ('Dinner Party', 'SOCIALISATION', true, 21, NOW() + INTERVAL '20 days', NOW() + INTERVAL '20 days' + INTERVAL '3 hours'),
    ('Morning Jog', 'SPORTS', true, 22, NOW() + INTERVAL '21 days', NOW() + INTERVAL '21 days' + INTERVAL '1 hour'),
    ('Music Festival', 'SOCIALISATION', true, 23, NOW() + INTERVAL '22 days', NOW() + INTERVAL '22 days' + INTERVAL '5 hours'),
    ('Grilling BBQ', 'CHORES', true, 24, NOW() + INTERVAL '23 days', NOW() + INTERVAL '23 days' + INTERVAL '2.5 hours'),
    ('Yoga Retreat', 'HEALTH', true, 25, NOW() + INTERVAL '24 days', NOW() + INTERVAL '24 days' + INTERVAL '6 hours'),
    ('Gardening', 'CHORES', true, 26, NOW() + INTERVAL '25 days', NOW() + INTERVAL '25 days' + INTERVAL '2 hours'),
    ('Team Building Event', 'WORK', true, 27, NOW() + INTERVAL '26 days', NOW() + INTERVAL '26 days' + INTERVAL '4 hours'),
    ('Rock Climbing', 'SPORTS', true, 28, NOW() + INTERVAL '27 days', NOW() + INTERVAL '27 days' + INTERVAL '2.5 hours'),
    ('Reading Club', 'SOCIALISATION', true, 29, NOW() + INTERVAL '28 days', NOW() + INTERVAL '28 days' + INTERVAL '1.5 hours'),
    ('Home Renovation', 'CHORES', true, 30, NOW() + INTERVAL '29 days', NOW() + INTERVAL '29 days' + INTERVAL '8 hours'),
    ('Tech Meetup', 'WORK', true, 31, NOW() + INTERVAL '30 days', NOW() + INTERVAL '30 days' + INTERVAL '3 hours'),
    ('Beach Volleyball', 'SPORTS', true, 32, NOW() + INTERVAL '31 days', NOW() + INTERVAL '31 days' + INTERVAL '2 hours'),
    ('Cooking Class', 'CHORES', true, 33, NOW() + INTERVAL '32 days', NOW() + INTERVAL '32 days' + INTERVAL '2.5 hours'),
    ('Networking Event', 'SOCIALISATION', true, 34, NOW() + INTERVAL '33 days', NOW() + INTERVAL '33 days' + INTERVAL '4 hours'),
    ('Painting Workshop', 'RELAXATION', true, 35, NOW() + INTERVAL '34 days', NOW() + INTERVAL '34 days' + INTERVAL '2 hours'),
    ('Volunteering', 'SOCIALISATION', true, 36, NOW() + INTERVAL '35 days', NOW() + INTERVAL '35 days' + INTERVAL '5 hours'),
    ('Business Trip', 'WORK', true, 37, NOW() + INTERVAL '36 days', NOW() + INTERVAL '36 days' + INTERVAL '8 hours'),
    ('Dance Class', 'SPORTS', true, 38, NOW() + INTERVAL '37 days', NOW() + INTERVAL '37 days' + INTERVAL '1.5 hours'),
    ('Stargazing', 'RELAXATION', true, 39, NOW() + INTERVAL '38 days', NOW() + INTERVAL '38 days' + INTERVAL '2 hours'),
    ('Home Office Day', 'WORK', true, 40, NOW() + INTERVAL '39 days', NOW() + INTERVAL '39 days' + INTERVAL '8 hours'),
    ('Family Picnic', 'SOCIALISATION', true, 41, NOW() + INTERVAL '40 days', NOW() + INTERVAL '40 days' + INTERVAL '4 hours'),
    ('Mountain Biking', 'SPORTS', true, 42, NOW() + INTERVAL '41 days', NOW() + INTERVAL '41 days' + INTERVAL '2.5 hours'),
    ('Book Club Meeting', 'SOCIALISATION', true, 43, NOW() + INTERVAL '42 days', NOW() + INTERVAL '42 days' + INTERVAL '1.5 hours'),
    ('DIY Home Project', 'CHORES', true, 44, NOW() + INTERVAL '43 days', NOW() + INTERVAL '43 days' + INTERVAL '5 hours'),
    ('Spa Day', 'RELAXATION', true, 45, NOW() + INTERVAL '44 days', NOW() + INTERVAL '44 days' + INTERVAL '6 hours'),
    ('Workout Class', 'SPORTS', true, 46, NOW() + INTERVAL '45 days', NOW() + INTERVAL '45 days' + INTERVAL '1.5 hours'),
    ('Podcast Recording', 'WORK', true, 47, NOW() + INTERVAL '46 days', NOW() + INTERVAL '46 days' + INTERVAL '2 hours'),
    ('Photography Expedition', 'RELAXATION', true, 48, NOW() + INTERVAL '47 days', NOW() + INTERVAL '47 days' + INTERVAL '4 hours'),
    ('Karaoke Night', 'SOCIALISATION', true, 49, NOW() + INTERVAL '48 days', NOW() + INTERVAL '48 days' + INTERVAL '3 hours'),
    ('Financial Planning', 'WORK', true, 50, NOW() + INTERVAL '49 days', NOW() + INTERVAL '49 days' + INTERVAL '2 hours');
