
INSERT INTO todos (title, category, priority, user_id)
VALUES
    ('Take out the trash', 'CHORES', true, 1),
    ('Play favorite song', 'RELAXATION', false, 2),
    ('Call a friend', 'SOCIALISATION', true, 3),
    ('Read a chapter', 'RELAXATION', true, 4),
    ('Write in journal', 'RELAXATION', false, 5),
    ('Quick workout', 'SPORTS', true, 6),
    ('Send thank you email', 'WORK', false, 7),
    ('Water the plants', 'CHORES', true, 8),
    ('Reply to messages', 'SOCIALISATION', true, 9),
    ('Organize closet', 'CHORES', false, 10),
    ('Plan next week', 'WORK', false, 11),
    ('Fix a leaky faucet', 'CHORES', false, 12),
    ('Visit an art gallery', 'SOCIALISATION', true, 13),
    ('Explore a new art exhibition', 'SOCIALISATION', true, 14),
    ('Host a movie night with friends', 'SOCIALISATION', true, 15),
    ('Host a game night', 'SOCIALISATION', true, 16),
    ('Send a thank-you note to a colleague', 'WORK', false, 17),
    ('Attend a community gardening event', 'CHORES', false, 18),
    ('Listen to a favorite podcast episode', 'RELAXATION', true, 19),
    ('Join a photography expedition', 'SOCIALISATION', true, 20),
    ('Water the garden plants', 'CHORES', true, 21),
    ('Send a thank-you note to a colleague', 'WORK', false, 22),
    ('Water the garden plants', 'CHORES', true, 23),
    ('Declutter the living room', 'CHORES', false, 24),
    ('Organize paperwork', 'CHORES', false, 25),
    ('Organize a family picnic', 'SOCIALISATION', true, 26),
    ('Plant flowers in the garden', 'CHORES', true, 27),
    ('Attend a community gardening event', 'CHORES', false, 28),
    ('Listen to a favorite podcast episode', 'RELAXATION', true, 29),
    ('Host a virtual book club meeting', 'SOCIALISATION', true, 30),
    ('Host a virtual book club meeting', 'SOCIALISATION', true, 31),
    ('Host a virtual book club meeting', 'SOCIALISATION', true, 32),
    ('Join a photography expedition', 'SOCIALISATION', true, 33),
    ('Learn a new recipe', 'CHORES', false, 34),
    ('Take out the trash', 'CHORES', true, 35),
    ('Play favorite song', 'RELAXATION', false, 36),
    ('Call a friend', 'SOCIALISATION', true, 37),
    ('Read a chapter', 'RELAXATION', true, 38),
    ('Write in journal', 'RELAXATION', false, 39),
    ('Quick workout', 'SPORTS', true, 40),
    ('Send thank you email', 'WORK', false, 41),
    ('Water the plants', 'CHORES', true, 42),
    ('Reply to messages', 'SOCIALISATION', true, 43),
    ('Organize closet', 'CHORES', false, 44),
    ('Take out the trash', 'CHORES', true, 45),
    ('Play favorite song', 'RELAXATION', false, 46),
    ('Call a friend', 'SOCIALISATION', true, 47),
    ('Read a chapter', 'RELAXATION', true, 48),
    ('Write in journal', 'RELAXATION', false, 49),
    ('Quick workout', 'SPORTS', true, 50),
    ('Send thank you email', 'WORK', false, 51),
    ('Water the plants', 'CHORES', true, 52),
    ('Reply to messages', 'SOCIALISATION', true, 53),
    ('Organize closet', 'CHORES', false, 54),
    ('Plan next week', 'WORK', false, 55),
    ('Fix a leaky faucet', 'CHORES', false, 56),
    ('Visit an art gallery', 'SOCIALISATION', true, 57),
    ('Explore a new art exhibition', 'SOCIALISATION', true, 58),
    ('Host a movie night with friends', 'SOCIALISATION', true, 59),
    ('Host a game night', 'SOCIALISATION', true, 60),
    ('Send a thank-you note to a colleague', 'WORK', false, 61),
    ('Attend a community gardening event', 'CHORES', false, 62),
    ('Listen to a favorite podcast episode', 'RELAXATION', true, 63),
    ('Join a photography expedition', 'SOCIALISATION', true, 64),
    ('Water the garden plants', 'CHORES', true, 65),
    ('Take out the trash', 'CHORES', true, 66),
    ('Play favorite song', 'RELAXATION', false, 67),
    ('Call a friend', 'SOCIALISATION', true, 68),
    ('Read a chapter', 'RELAXATION', true, 69),
    ('Write in journal', 'RELAXATION', false, 70),
    ('Quick workout', 'SPORTS', true, 71),
    ('Send thank you email', 'WORK', false, 72),
    ('Water the plants', 'CHORES', true, 73),
    ('Reply to messages', 'SOCIALISATION', true, 74),
    ('Organize closet', 'CHORES', false, 75),
    ('Plan next week', 'WORK', false, 76),
    ('Fix a leaky faucet', 'CHORES', false, 77),
    ('Visit an art gallery', 'SOCIALISATION', true, 78),
    ('Explore a new art exhibition', 'SOCIALISATION', true, 79),
    ('Host a movie night with friends', 'SOCIALISATION', true, 80),
    ('Host a game night', 'SOCIALISATION', true, 81),
    ('Send a thank-you note to a colleague', 'WORK', false, 82),
    ('Attend a community gardening event', 'CHORES', false, 83),
    ('Listen to a favorite podcast episode', 'RELAXATION', true, 84),
    ('Join a photography expedition', 'SOCIALISATION', true, 85),
    ('Water the garden plants', 'CHORES', true, 86),
    ('Take out the trash', 'CHORES', true, 87),
    ('Play favorite song', 'RELAXATION', false, 88),
    ('Call a friend', 'SOCIALISATION', true, 89),
    ('Read a chapter', 'RELAXATION', true, 90),
    ('Write in journal', 'RELAXATION', false, 91),
    ('Quick workout', 'SPORTS', true, 92),
    ('Send thank you email', 'WORK', false, 93),
    ('Water the plants', 'CHORES', true, 94),
    ('Reply to messages', 'SOCIALISATION', true, 95),
    ('Organize closet', 'CHORES', false, 96),
    ('Plan next week', 'WORK', false, 97),
    ('Fix a leaky faucet', 'CHORES', false, 98),
    ('Visit an art gallery', 'SOCIALISATION', true, 99),
    ('Explore a new art exhibition', 'SOCIALISATION', true, 100),
    ('Take out the trash', 'CHORES', true, 17),
    ('Play favorite song', 'RELAXATION', false, 41),
    ('Call a friend', 'SOCIALISATION', true, 19),
    ('Read a chapter', 'RELAXATION', true, 2),
    ('Write in journal', 'RELAXATION', false, 20),
    ('Quick workout', 'SPORTS', true, 33),
    ('Send thank you email', 'WORK', false, 36),
    ('Water the plants', 'CHORES', true, 31),
    ('Reply to messages', 'SOCIALISATION', true, 4),
    ('Organize closet', 'CHORES', false, 78),
    ('Plan next week', 'WORK', false, 4),
    ('Fix a leaky faucet', 'CHORES', false, 26),
    ('Visit an art gallery', 'SOCIALISATION', true, 42),
    ('Explore a new art exhibition', 'SOCIALISATION', true, 13),
    ('Host a movie night with friends', 'SOCIALISATION', true, 9),
    ('Host a game night', 'SOCIALISATION', true, 12),
    ('Send a thank-you note to a colleague', 'WORK', false, 7),
    ('Attend a community gardening event', 'CHORES', false, 45),
    ('Listen to a favorite podcast episode', 'RELAXATION', true, 33),
    ('Listen to a favorite podcast episode', 'RELAXATION', true, 32),
    ('Listen to a favorite podcast episode', 'RELAXATION', true, 83),
    ('Listen to a favorite podcast episode', 'RELAXATION', true, 93),
    ('Join a photography expedition', 'SOCIALISATION', true, 48),
    ('Water the garden plants', 'CHORES', true, 26),
    ('Send a thank-you note to a colleague', 'WORK', false, 72),
    ('Water the garden plants', 'CHORES', true, 29),
    ('Declutter the living room', 'CHORES', false, 91),
    ('Organize paperwork', 'CHORES', false, 87),
    ('Organize a family picnic', 'SOCIALISATION', true, 64),
    ('Plant flowers in the garden', 'CHORES', true, 14),
    ('Attend a community gardening event', 'CHORES', false, 21),
    ('Listen to a favorite podcast episode', 'RELAXATION', true, 31),
    ('Host a virtual book club meeting', 'SOCIALISATION', true, 29),
    ('Host a virtual book club meeting', 'SOCIALISATION', true, 49),
    ('Host a virtual book club meeting', 'SOCIALISATION', true, 79),
    ('Join a photography expedition', 'SOCIALISATION', true, 38),
    ('Learn a new recipe', 'CHORES', false, 34);